"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], clamp=(v,a=0,b=255)=>Math.max(a,Math.min(b,v));
const state={introMode:"rgb",edgeMode:"input",thresholdMode:"global",clusters:[],selected:new Set(),image:null};
$$(".note").forEach(note=>note.remove());
function scene(x,w,h,dim=false){const g=x.createLinearGradient(0,0,w,dim?h*.2:0);g.addColorStop(0,dim?"#34424d":"#7fc8d1");g.addColorStop(1,dim?"#dbcda7":"#e6d8ad");x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle="#405361";x.fillRect(w*.07,h*.15,w*.31,h*.62);x.fillStyle="#f1d877";x.fillRect(w*.11,h*.22,w*.09,h*.18);x.fillStyle="#d5efec";x.fillRect(w*.24,h*.22,w*.09,h*.18);x.fillStyle="#202e37";x.fillRect(w*.105,h*.51,w*.23,h*.055);x.fillStyle=dim?"#777260":"#ed6249";x.beginPath();x.arc(w*.62,h*.52,h*.19,0,Math.PI*2);x.fill();x.fillStyle="#18262e";x.fillRect(w*.57,h*.28,w*.1,h*.09);x.fillStyle="#c8f04a";x.beginPath();x.moveTo(w*.72,h*.75);x.lineTo(w*.91,h*.38);x.lineTo(w*.94,h*.78);x.closePath();x.fill();x.strokeStyle="#17232a";x.lineWidth=8;x.beginPath();x.moveTo(w*.04,h*.87);x.lineTo(w*.96,h*.87);x.stroke()}
function drawCover(x,image,dx,dy,w,h){const scale=Math.max(w/image.naturalWidth,h/image.naturalHeight),sw=w/scale,sh=h/scale,sx=(image.naturalWidth-sw)/2,sy=(image.naturalHeight-sh)/2;x.drawImage(image,sx,sy,sw,sh,dx,dy,w,h)}
const generatedScene=scene;
function sourceScene(x,w,h,dim=false){if(!state.image)return generatedScene(x,w,h,dim);drawCover(x,state.image,0,0,w,h);if(dim){x.fillStyle="rgba(16,24,32,.18)";x.fillRect(0,0,w,h)}}
scene=sourceScene;
function gray(img){const g=new Uint8ClampedArray(img.width*img.height);for(let i=0,p=0;i<img.data.length;i+=4,p++)g[p]=.299*img.data[i]+.587*img.data[i+1]+.114*img.data[i+2];return g}
function putGray(x,g,w,h,accent=false){const o=x.createImageData(w,h);for(let p=0,i=0;p<g.length;p++,i+=4){const v=g[p];if(accent&&v){o.data[i]=200;o.data[i+1]=240;o.data[i+2]=74}else o.data[i]=o.data[i+1]=o.data[i+2]=v;o.data[i+3]=255}x.putImageData(o,0,0)}
function sobel(g,w,h,mode,t){const o=new Uint8ClampedArray(g.length),kx=[-1,0,1,-2,0,2,-1,0,1],ky=[-1,-2,-1,0,0,0,1,2,1];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let sx=0,sy=0,k=0;for(let j=-1;j<2;j++)for(let i=-1;i<2;i++,k++){const v=g[(y+j)*w+x+i];sx+=v*kx[k];sy+=v*ky[k]}const v=mode==="sobelX"?Math.abs(sx):mode==="sobelY"?Math.abs(sy):Math.hypot(sx,sy);o[y*w+x]=v>=t?clamp(v):0}return o}
function morph(src,w,h,type,r){if(type==="none")return src;const pass=(a,max)=>{const o=new Uint8ClampedArray(a.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let v=max?0:255;for(let j=-r;j<=r;j++)for(let i=-r;i<=r;i++){const q=a[clamp(y+j,0,h-1)*w+clamp(x+i,0,w-1)];v=max?Math.max(v,q):Math.min(v,q)}o[y*w+x]=v}return o};if(type==="dilate")return pass(src,1);if(type==="erode")return pass(src,0);if(type==="close")return pass(pass(src,1),0);return pass(pass(src,0),1)}
function localThreshold(g,w,h,size,offset){const I=new Float64Array((w+1)*(h+1));for(let y=1;y<=h;y++){let row=0;for(let x=1;x<=w;x++){row+=g[(y-1)*w+x-1];I[y*(w+1)+x]=I[(y-1)*(w+1)+x]+row}}const o=new Uint8ClampedArray(g.length),r=size>>1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const x0=Math.max(0,x-r),x1=Math.min(w-1,x+r),y0=Math.max(0,y-r),y1=Math.min(h-1,y+r),sum=I[(y1+1)*(w+1)+x1+1]-I[y0*(w+1)+x1+1]-I[(y1+1)*(w+1)+x0]+I[y0*(w+1)+x0],m=sum/((x1-x0+1)*(y1-y0+1));o[y*w+x]=g[y*w+x]>m-(offset-128)/4?255:0}return o}
function largest(b,w,h){const seen=new Uint8Array(b.length);let best=[];for(let s=0;s<b.length;s++){if(!b[s]||seen[s])continue;const q=[s],r=[];seen[s]=1;while(q.length){const p=q.pop();r.push(p);const x=p%w,y=p/w|0,n=[];if(x)n.push(p-1);if(x<w-1)n.push(p+1);if(y)n.push(p-w);if(y<h-1)n.push(p+w);for(const z of n)if(b[z]&&!seen[z])seen[z]=1,q.push(z)}if(r.length>best.length)best=r}const o=new Uint8ClampedArray(b.length);best.forEach(p=>o[p]=255);return o}
function boundary(b,w,h){const o=new Uint8ClampedArray(b.length);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x;if(b[p]&&(!b[p-1]||!b[p+1]||!b[p-w]||!b[p+w]))o[p]=255}return o}
function openModule(id){$("#modules").hidden=true;$("#workspace").hidden=false;$$(".demo").forEach(x=>x.classList.toggle("active",x.id===id));const d=document.getElementById(id);$("#module-counter").textContent=d.dataset.number+" / 9";location.hash="workspace";renderAll()}
$$("[data-open]").forEach(b=>b.onclick=()=>openModule(b.dataset.open));$("#back-button").onclick=()=>{$("#workspace").hidden=true;$("#modules").hidden=false;location.hash="modules"};$("#present-button").onclick=()=>document.body.classList.toggle("presenting");
function loadImageFile(file){if(!file||!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{state.image=image;state.templateRect=[Math.round($("#template-canvas").width*.35),Math.round($("#template-canvas").height*.35),120,100];$("#upload-name").textContent=file.name;$("#clear-upload").hidden=false;makePoster();runKmeans();renderAll()};image.src=reader.result};reader.readAsDataURL(file)}
$("#image-upload").addEventListener("change",e=>loadImageFile(e.target.files[0]));
const uploadDropzone=$("#upload-dropzone");let uploadDragDepth=0;["dragenter","dragover","drop"].forEach(name=>window.addEventListener(name,e=>{if([...e.dataTransfer?.types||[]].includes("Files"))e.preventDefault()}));uploadDropzone.addEventListener("dragenter",e=>{e.preventDefault();uploadDragDepth++;uploadDropzone.classList.add("dragging")});uploadDropzone.addEventListener("dragover",e=>{e.preventDefault();e.dataTransfer.dropEffect="copy"});uploadDropzone.addEventListener("dragleave",()=>{uploadDragDepth=Math.max(0,uploadDragDepth-1);if(!uploadDragDepth)uploadDropzone.classList.remove("dragging")});uploadDropzone.addEventListener("drop",e=>{e.preventDefault();uploadDragDepth=0;uploadDropzone.classList.remove("dragging");loadImageFile(e.dataTransfer.files[0])});
$("#clear-upload").onclick=()=>{state.image=null;state.templateRect=[62,194,76,92];$("#image-upload").value="";$("#upload-name").textContent="Generated sample";$("#clear-upload").hidden=true;makePoster();runKmeans();renderAll()};
$$(".options").forEach(group=>group.onclick=e=>{const b=e.target.closest("button");if(!b)return;$$("button",group).forEach(x=>x.classList.toggle("active",x===b));state[group.dataset.control.replace("-mode","Mode")]=b.dataset.value;renderDemo(group.closest(".demo").id)});
const intro=$("#intro-canvas"),ix=intro.getContext("2d");function renderIntro(){scene(ix,intro.width,intro.height);const img=ix.getImageData(0,0,intro.width,intro.height),mode=state.introMode,m=$("#gray-method").value;if(mode==="rgb")return;for(let i=0;i<img.data.length;i+=4){const r=img.data[i],g=img.data[i+1],b=img.data[i+2],v=mode==="red"?r:mode==="green"?g:mode==="blue"?b:m==="average"?(r+g+b)/3:m==="red"?r:.299*r+.587*g+.114*b;img.data[i]=img.data[i+1]=img.data[i+2]=v}ix.putImageData(img,0,0)}
intro.onpointermove=e=>{const r=intro.getBoundingClientRect(),x=clamp(Math.floor((e.clientX-r.left)*intro.width/r.width),0,intro.width-1),y=clamp(Math.floor((e.clientY-r.top)*intro.height/r.height),0,intro.height-1),p=ix.getImageData(x,y,1,1).data;$("#pixel-readout").textContent="x "+x+" · y "+y+" · R "+p[0]+" · G "+p[1]+" · B "+p[2]};
function renderHistogram(){const c=$("#hist-image"),x=c.getContext("2d");scene(x,c.width,c.height);const img=x.getImageData(0,0,c.width,c.height),exp=+$("#exposure").value,con=+$("#contrast").value/100;for(let i=0;i<img.data.length;i+=4)for(let z=0;z<3;z++)img.data[i+z]=clamp((img.data[i+z]-128)*con+128+exp);if($("#equalize").checked){const g=gray(img),h=new Uint32Array(256);g.forEach(v=>h[v]++);const cdf=new Uint32Array(256);h.reduce((a,v,i)=>cdf[i]=a+v,0);const first=cdf.find(v=>v),den=g.length-first||1;for(let i=0,p=0;i<img.data.length;i+=4,p++){const old=g[p]||1,n=clamp((cdf[old]-first)*255/den),q=n/old;img.data[i]=clamp(img.data[i]*q);img.data[i+1]=clamp(img.data[i+1]*q);img.data[i+2]=clamp(img.data[i+2]*q)}}x.putImageData(img,0,0);const g=gray(img),bins=+$("#bins").value,h=new Uint32Array(bins);g.forEach(v=>h[Math.min(bins-1,v*bins/256|0)]++);const hc=$("#hist-plot"),hx=hc.getContext("2d"),max=Math.max(...h);hx.fillStyle="#242b2e";hx.fillRect(0,0,hc.width,hc.height);hx.fillStyle="#c8f04a";h.forEach((v,i)=>hx.fillRect(i*hc.width/bins,hc.height-v/max*(hc.height-15),Math.max(1,hc.width/bins-1),v/max*(hc.height-15)));$("#exposure-out").textContent=exp;$("#contrast-out").textContent=con.toFixed(2);$("#bins-out").textContent=bins}
const edge=$("#edge-canvas"),ex=edge.getContext("2d");function renderEdges(){scene(ex,edge.width,edge.height);if(state.edgeMode==="input")return;let o=sobel(gray(ex.getImageData(0,0,edge.width,edge.height)),edge.width,edge.height,state.edgeMode,+$("#edge-threshold").value);o=morph(o,edge.width,edge.height,$("#morph-mode").value,+$("#morph-size").value);putGray(ex,o,edge.width,edge.height,true);$("#edge-view-label").textContent=state.edgeMode+" · "+$("#morph-mode").value}
const tc=$("#threshold-canvas"),tx=tc.getContext("2d");function renderThreshold(){scene(tx,tc.width,tc.height,true);const g=gray(tx.getImageData(0,0,tc.width,tc.height)),v=+$("#threshold-value").value;let b;if(state.thresholdMode==="adaptive")b=localThreshold(g,tc.width,tc.height,+$("#block-size").value,v);else{b=new Uint8ClampedArray(g.length);g.forEach((z,i)=>b[i]=z>v?255:0)}if(state.thresholdMode==="contours"){const o=boundary($("#largest-contour").checked?largest(b,tc.width,tc.height):b,tc.width,tc.height);putGray(tx,b,tc.width,tc.height);const img=tx.getImageData(0,0,tc.width,tc.height);o.forEach((z,p)=>{if(z){const i=p*4;img.data[i]=240;img.data[i+1]=96;img.data[i+2]=73}});tx.putImageData(img,0,0)}else putGray(tx,b,tc.width,tc.height);$("#threshold-view-label").textContent=state.thresholdMode}
function nearest(p,c){let n=0,d=Infinity,perceptual=$("#k-space").value==="lab";c.forEach((q,i)=>{const v=(p[0]-q[0])**2*(perceptual?.45:1)+(p[1]-q[1])**2*(perceptual?1.2:1)+(p[2]-q[2])**2*(perceptual?.35:1);if(v<d)d=v,n=i});return n}
function runKmeans(){const c=$("#kmeans-canvas"),x=c.getContext("2d");scene(x,c.width,c.height);const img=x.getImageData(0,0,c.width,c.height),k=+$("#k-value").value,p=[];for(let y=2;y<c.height;y+=6)for(let xx=2;xx<c.width;xx+=6){const i=(y*c.width+xx)*4;p.push([img.data[i],img.data[i+1],img.data[i+2]])}let centers=Array.from({length:k},()=>p[Math.random()*p.length|0].slice());for(let it=0;it<7;it++){const sums=Array.from({length:k},()=>[0,0,0,0]);p.forEach(v=>{const s=sums[nearest(v,centers)];s[0]+=v[0];s[1]+=v[1];s[2]+=v[2];s[3]++});centers=centers.map((q,i)=>sums[i][3]?sums[i].slice(0,3).map(v=>v/sums[i][3]):q)}state.clusters=centers;state.selected=new Set(centers.map((_,i)=>i));renderKmeans()}
function renderKmeans(){if(!state.clusters.length)return;const c=$("#kmeans-canvas"),x=c.getContext("2d");scene(x,c.width,c.height);const img=x.getImageData(0,0,c.width,c.height),mask=$("#k-mask").checked;for(let i=0;i<img.data.length;i+=4){const n=nearest([img.data[i],img.data[i+1],img.data[i+2]],state.clusters),q=state.clusters[n],on=state.selected.has(n);img.data[i]=mask&&!on?28:q[0];img.data[i+1]=mask&&!on?30:q[1];img.data[i+2]=mask&&!on?31:q[2]}x.putImageData(img,0,0);const p=$("#palette");p.innerHTML="";state.clusters.forEach((q,i)=>{const b=document.createElement("button");b.style.background="rgb("+q.join()+")";b.classList.toggle("off",!state.selected.has(i));b.onclick=()=>{state.selected.has(i)?state.selected.delete(i):state.selected.add(i);renderKmeans()};p.append(b)})}
function target(x,cx,cy,s=1,r=0){x.save();x.translate(cx,cy);x.rotate(r);x.scale(s,s);x.fillStyle="#f06449";x.fillRect(-35,-48,70,96);x.fillStyle="#17232a";x.fillRect(-18,-29,36,16);x.strokeStyle="#f06449";x.lineWidth=11;x.beginPath();x.arc(38,0,24,-Math.PI/2,Math.PI/2);x.stroke();x.restore()}
function renderTemplate(){
  const c=$("#template-canvas"),x=c.getContext("2d"),heat=$("#template-heatmap"),hx=heat.getContext("2d"),preview=$("#template-preview"),px=preview.getContext("2d");
  const scale=+$("#target-scale").value/100,angle=+$("#target-rotation").value*Math.PI/180,gain=+$("#heatmap-opacity").value/100;
  if(state.image)drawCover(x,state.image,0,0,c.width,c.height);else{x.fillStyle="#d9d5c9";x.fillRect(0,0,c.width,c.height);for(let i=0;i<8;i++){x.fillStyle=i%2?"#8aa0a5":"#b7a77c";x.fillRect(40+i*83,65+(i%3)*65,50,40)}target(x,100,240,.85);target(x,470,170,.85)}
  const source=x.getImageData(0,0,c.width,c.height),g=gray(source),r=state.templateRect||[62,194,76,92],cw=Math.max(18,Math.round(r[2]*scale)),ch=Math.max(18,Math.round(r[3]*scale)),step=12,samples=9,responses=[];let best={score:-1,x:0,y:0};
  for(let cy=ch/2;cy<c.height-ch/2;cy+=step)for(let cx=cw/2;cx<c.width-cw/2;cx+=step){if(Math.abs(cx-(r[0]+r[2]/2))<(r[2]+cw)/2&&Math.abs(cy-(r[1]+r[3]/2))<(r[3]+ch)/2)continue;let error=0,count=0;for(let sy=0;sy<samples;sy++)for(let sx=0;sx<samples;sx++){const u=sx/(samples-1)-.5,v=sy/(samples-1)-.5,ti=clamp(Math.round(r[1]+(v+.5)*r[3]),0,c.height-1)*c.width+clamp(Math.round(r[0]+(u+.5)*r[2]),0,c.width-1),rx=u*cw*Math.cos(angle)-v*ch*Math.sin(angle),ry=u*cw*Math.sin(angle)+v*ch*Math.cos(angle),qi=clamp(Math.round(cy+ry),0,c.height-1)*c.width+clamp(Math.round(cx+rx),0,c.width-1);error+=Math.abs(g[ti]-g[qi]);count++}const score=1-error/(count*255);responses.push([cx,cy,score]);if(score>best.score)best={score,x:cx,y:cy}}
  px.fillStyle="#242b2e";px.fillRect(0,0,preview.width,preview.height);px.drawImage(c,r[0],r[1],r[2],r[3],0,0,preview.width,preview.height);
  hx.fillStyle="#172027";hx.fillRect(0,0,heat.width,heat.height);responses.forEach(q=>{const v=clamp((q[2]-(.65-gain*.25))/(1-(.65-gain*.25)),0,1);hx.fillStyle="rgb("+Math.round(25+230*v)+","+Math.round(45+185*v)+","+Math.round(130-90*v)+")";hx.fillRect(q[0]-step/2,q[1]-step/2,step+1,step+1)});hx.strokeStyle="#faf9f5";hx.lineWidth=3;hx.strokeRect(best.x-cw/2,best.y-ch/2,cw,ch);
  x.putImageData(source,0,0);x.strokeStyle="#57c7d4";x.lineWidth=4;x.strokeRect(...r);
  $("#match-score").textContent=($("#template-method").value==="sqdiff"?1-best.score:best.score).toFixed(2);$("#target-scale-out").textContent=scale.toFixed(2);$("#target-rotation-out").textContent=$("#target-rotation").value+" deg";$("#heatmap-opacity-out").textContent=Math.round(gain*100)+"%";
}
const templateCanvas=$("#template-canvas"),templateDrop=$("#template-dropzone");let templateStart=null;function templatePoint(e){const b=templateCanvas.getBoundingClientRect();return[clamp((e.clientX-b.left)*templateCanvas.width/b.width,0,templateCanvas.width),clamp((e.clientY-b.top)*templateCanvas.height/b.height,0,templateCanvas.height)]}templateCanvas.addEventListener("pointerdown",e=>{templateStart=templatePoint(e);templateCanvas.setPointerCapture(e.pointerId)});templateCanvas.addEventListener("pointermove",e=>{if(!templateStart)return;const p=templatePoint(e),x=Math.min(p[0],templateStart[0]),y=Math.min(p[1],templateStart[1]),w=Math.abs(p[0]-templateStart[0]),h=Math.abs(p[1]-templateStart[1]);if(w>12&&h>12){state.templateRect=[x,y,w,h];renderTemplate()}});templateCanvas.addEventListener("pointerup",()=>templateStart=null);["dragenter","dragover"].forEach(name=>templateDrop.addEventListener(name,e=>{e.preventDefault();templateDrop.classList.add("dragging")}));["dragleave","drop"].forEach(name=>templateDrop.addEventListener(name,e=>{e.preventDefault();templateDrop.classList.remove("dragging")}));templateDrop.addEventListener("drop",e=>loadImageFile(e.dataTransfer.files[0]));
function renderFeatures(){
  const c=$("#feature-canvas"),x=c.getContext("2d"),left=20,top=40,w=400,h=360,right=480,angle=+$("#feature-rotation").value*Math.PI/180,scale=+$("#feature-scale").value/100,t=+$("#feature-threshold").value,ratio=+$("#ratio").value/100,filter=$("#ransac").checked,method=$("#feature-method").value;
  const base=document.createElement("canvas");base.width=w;base.height=h;const bx=base.getContext("2d");if(state.image)drawCover(bx,state.image,0,0,w,h);else generatedScene(bx,w,h);
  x.fillStyle="#20272b";x.fillRect(0,0,c.width,c.height);x.drawImage(base,left,top);
  x.save();x.beginPath();x.rect(right,top,w,h);x.clip();x.translate(right+w/2,top+h/2);x.rotate(angle);x.scale(scale,scale);x.drawImage(base,-w/2,-h/2);x.restore();
  x.strokeStyle="#83898a";x.strokeRect(left,top,w,h);x.strokeRect(right,top,w,h);x.fillStyle="#eef0e8";x.font="11px Consolas";x.fillText("VIEW A",left,24);x.fillText("VIEW B · "+$("#feature-rotation").value+" deg · "+scale.toFixed(2)+"x",right,24);
  const g=gray(bx.getImageData(0,0,w,h)),candidates=[];for(let py=4;py<h-4;py+=6)for(let px=4;px<w-4;px+=6){const gx=Math.abs(g[py*w+px+2]-g[py*w+px-2]),gy=Math.abs(g[(py+2)*w+px]-g[(py-2)*w+px]),score=Math.min(gx,gy);if(score>t*1.35)candidates.push([px,py,score])}candidates.sort((a,b)=>b[2]-a[2]);const points=[],limit=method==="harris"?55:method==="sift"?42:65;for(const p of candidates){if(points.every(q=>Math.hypot(q[0]-p[0],q[1]-p[1])>15))points.push(p);if(points.length>=limit)break}
  const keep=Math.max(1,Math.round(points.length*ratio)),visible=[];for(let i=0;i<keep;i++){const p=points[i],dx=(p[0]-w/2)*scale,dy=(p[1]-h/2)*scale,qx=w/2+dx*Math.cos(angle)-dy*Math.sin(angle),qy=h/2+dx*Math.sin(angle)+dy*Math.cos(angle);if(qx<0||qx>w||qy<0||qy>h)continue;const bad=!filter&&i%9===0,q=bad?[right+30+(i*73)%(w-60),top+25+(i*47)%(h-50)]:[right+qx,top+qy],a=[left+p[0],top+p[1]];visible.push([a,q,bad,p[2]])}
  visible.forEach(m=>{x.strokeStyle=m[2]?"rgba(240,96,73,.72)":"rgba(87,199,212,.68)";x.lineWidth=1;x.beginPath();x.moveTo(...m[0]);x.lineTo(...m[1]);x.stroke();const radius=method==="sift"?3+5*m[3]/255:4;x.fillStyle=method==="harris"?"#c8f04a":"#faf9f5";[m[0],m[1]].forEach(p=>{x.beginPath();x.arc(p[0],p[1],radius,0,Math.PI*2);x.fill()})});
  $("#match-count").textContent=visible.length;$("#feature-threshold-out").textContent=t;$("#ratio-out").textContent=ratio.toFixed(2);$("#feature-rotation-out").textContent=$("#feature-rotation").value+" deg";$("#feature-scale-out").textContent=scale.toFixed(2);
}
function largestValidRectangle(mask,w,h){const heights=new Int32Array(w);let best={area:0,x:0,y:0,w:0,h:0};for(let y=0;y<h;y++){for(let x=0;x<w;x++)heights[x]=mask[y*w+x]?heights[x]+1:0;const stack=[];for(let x=0;x<=w;x++){const current=x===w?0:heights[x];while(stack.length&&heights[stack[stack.length-1]]>current){const index=stack.pop(),height=heights[index],left=stack.length?stack[stack.length-1]+1:0,width=x-left,area=width*height;if(area>best.area)best={area,x:left,y:y-height+1,w:width,h:height}}stack.push(x)}}return best}
function renderCalibration(){
  const c=$("#calibration-canvas"),x=c.getContext("2d"),k=+$("#distortion").value/100,showGrid=$("#calibration-grid").checked,w=c.width,h=c.height,source=document.createElement("canvas");source.width=w;source.height=h;const sx=source.getContext("2d");if(state.image)drawCover(sx,state.image,0,0,w,h);else generatedScene(sx,w,h);const input=sx.getImageData(0,0,w,h),output=x.createImageData(w,h),valid=new Uint8Array(w*h);
  let extent=0;for(let side=0;side<4;side++)for(let n=0;n<=400;n++){const t=-1+2*n/400,px=side<2?(side?1:-1):t,py=side<2?t:(side===2?-1:1),r2=px*px+py*py,f=1/(1-k*r2);extent=Math.max(extent,Math.abs(px*f),Math.abs(py*f))}extent=Math.max(extent,.001);
  for(let oy=0;oy<h;oy++)for(let ox=0;ox<w;ox++){const qx=(2*ox/(w-1)-1)*extent,qy=(2*oy/(h-1)-1)*extent,qr=Math.hypot(qx,qy),index=oy*w+ox,di=index*4;let radius=qr;if(qr>1e-9)for(let iteration=0;iteration<8;iteration++){const den=1-k*radius*radius,f=radius/den-qr,df=(1+k*radius*radius)/(den*den);radius=clamp(radius-f/df,0,3)}const factor=qr>1e-9?radius/qr:1,px=qx*factor,py=qy*factor,inside=Math.abs(px)<=1&&Math.abs(py)<=1&&Number.isFinite(px)&&Number.isFinite(py);valid[index]=inside?1:0;if(inside){const ix=clamp(Math.round((px+1)*.5*(w-1)),0,w-1),iy=clamp(Math.round((py+1)*.5*(h-1)),0,h-1),si=(iy*w+ix)*4;output.data[di]=input.data[si];output.data[di+1]=input.data[si+1];output.data[di+2]=input.data[si+2];output.data[di+3]=255}else{output.data[di]=16;output.data[di+1]=20;output.data[di+2]=22;output.data[di+3]=255}}
  x.putImageData(output,0,0);
  if(showGrid){x.strokeStyle="rgba(255,255,255,.72)";x.lineWidth=1;for(let axis=0;axis<2;axis++)for(let line=-10;line<=10;line++){x.beginPath();for(let n=0;n<=160;n++){const a=line/10,b=-1+2*n/160,px=axis?a:b,py=axis?b:a,r2=px*px+py*py,f=1/(1-k*r2),gx=(px*f/extent+1)*.5*w,gy=(py*f/extent+1)*.5*h;n?x.lineTo(gx,gy):x.moveTo(gx,gy)}x.stroke()}}
  const roi=largestValidRectangle(valid,w,h);x.strokeStyle="#62d18a";x.lineWidth=5;x.strokeRect(roi.x+2,roi.y+2,Math.max(0,roi.w-4),Math.max(0,roi.h-4));const sourceW=state.image?state.image.naturalWidth:w,sourceH=state.image?state.image.naturalHeight:h,reportedW=Math.round(sourceW*roi.w/w),reportedH=Math.round(sourceH*roi.h/h),kind=k<-.005?"Barrel":k>.005?"Pincushion":"None";$("#calibration-roi").textContent=reportedW+" × "+reportedH;$("#calibration-zoom").textContent=(1/extent).toFixed(2)+"×";$("#distortion-out").textContent=kind+" "+(k>=0?"+":"")+k.toFixed(2);
}
function solve(A,b){for(let i=0;i<b.length;i++){let m=i;for(let j=i+1;j<b.length;j++)if(Math.abs(A[j][i])>Math.abs(A[m][i]))m=j;[A[i],A[m]]=[A[m],A[i]];[b[i],b[m]]=[b[m],b[i]];const d=A[i][i]||1e-9;for(let j=i;j<A[i].length;j++)A[i][j]/=d;b[i]/=d;for(let k=0;k<b.length;k++)if(k!==i){const f=A[k][i];for(let j=i;j<A[k].length;j++)A[k][j]-=f*A[i][j];b[k]-=f*b[i]}}return b}
function homography(src,dst){const A=[],b=[];src.forEach(([x,y],i)=>{const u=dst[i][0],v=dst[i][1];A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)});return[...solve(A,b),1]}function project(h,x,y){const d=h[6]*x+h[7]*y+h[8];return[(h[0]*x+h[1]*y+h[2])/d,(h[3]*x+h[4]*y+h[5])/d]}
const ps=$("#perspective-source"),po=$("#perspective-output"),psx=ps.getContext("2d"),pox=po.getContext("2d"),poster=document.createElement("canvas");poster.width=ps.width;poster.height=ps.height;const pc=poster.getContext("2d");let points=[[118,90],[455,62],[490,340],[80,355]],drag=-1;
function makePoster(){pc.fillStyle="#536873";pc.fillRect(0,0,ps.width,ps.height);pc.fillStyle="#f4f1e8";pc.fillRect(105,55,355,300);pc.fillStyle="#f06449";pc.fillRect(125,75,315,260);pc.fillStyle="#171a1d";pc.font="900 58px Arial";pc.fillText("SEE",158,162);pc.fillText("THE",158,220);pc.fillText("MATRIX",158,278);pc.fillStyle="#c8f04a";pc.fillRect(125,300,315,35)}
function renderPerspective(){psx.drawImage(poster,0,0);psx.strokeStyle="#c8f04a";psx.lineWidth=4;psx.beginPath();points.forEach((p,i)=>i?psx.lineTo(...p):psx.moveTo(...p));psx.closePath();psx.stroke();points.forEach((p,i)=>{psx.fillStyle="#c8f04a";psx.beginPath();psx.arc(...p,10,0,Math.PI*2);psx.fill();psx.fillStyle="#171a1d";psx.fillText(i+1,p[0]-3,p[1]+4)});const h=homography([[0,0],[po.width-1,0],[po.width-1,po.height-1],[0,po.height-1]],points),src=pc.getImageData(0,0,ps.width,ps.height),out=pox.createImageData(po.width,po.height);for(let y=0;y<po.height;y++)for(let x=0;x<po.width;x++){const q=project(h,x,y),xx=Math.round(q[0]),yy=Math.round(q[1]),di=(y*po.width+x)*4;if(xx>=0&&xx<ps.width&&yy>=0&&yy<ps.height){const si=(yy*ps.width+xx)*4;for(let z=0;z<4;z++)out.data[di+z]=src.data[si+z]}}pox.putImageData(out,0,0)}
function ppos(e){const r=ps.getBoundingClientRect();return[(e.clientX-r.left)*ps.width/r.width,(e.clientY-r.top)*ps.height/r.height]}ps.onpointerdown=e=>{const p=ppos(e);drag=points.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<25)};ps.onpointermove=e=>{if(drag<0)return;const p=ppos(e);points[drag]=[clamp(p[0],5,ps.width-5),clamp(p[1],5,ps.height-5)];renderPerspective()};ps.onpointerup=()=>drag=-1;$("#perspective-reset").onclick=()=>{points=[[70+Math.random()*100,45+Math.random()*90],[400+Math.random()*100,45+Math.random()*90],[420+Math.random()*100,285+Math.random()*85],[45+Math.random()*100,285+Math.random()*85]];renderPerspective()};
const generatedPoster=makePoster;makePoster=function(){if(state.image)drawCover(pc,state.image,0,0,ps.width,ps.height);else generatedPoster()};
function renderAll(){renderIntro();renderHistogram();renderEdges();renderThreshold();renderKmeans();renderTemplate();renderFeatures();renderCalibration();renderPerspective()}
function renderDemo(id){const renders={"intro-demo":renderIntro,"hist-demo":renderHistogram,"geometry-demo":renderPerspective,"edges-demo":renderEdges,"threshold-demo":renderThreshold,"kmeans-demo":renderKmeans,"template-demo":renderTemplate,"features-demo":renderFeatures,"calibration-demo":renderCalibration};if(renders[id])renders[id]()}
$$("input,select").forEach(el=>el.addEventListener("input",()=>{if(el.id==="k-value")runKmeans();else renderDemo(el.closest(".demo")?.id);$("#edge-threshold-out").textContent=$("#edge-threshold").value;$("#morph-size-out").textContent=$("#morph-size").value+" px";$("#threshold-value-out").textContent=$("#threshold-value").value;$("#block-size-out").textContent=$("#block-size").value+" px";$("#k-out").textContent=$("#k-value").value}));$("#k-rerun").onclick=runKmeans;
makePoster();runKmeans();renderAll();
